### ISSUE TITLE
Groups Don't have Descriptions in JSON API

### ISSUE THREAD

**Issue by jaredsmithse** [TeamCobra/ouroboros#90]
Right now the response given back from the `/groups` endpoint does not have the description of that group being returned in it's json representation.

**Comment by gemarcano** [comment]
The problem was that I forgot to output the contents of the group. #94 now has that ability. Please check to see if the JSON format is acceptable (in summary, a group has three keys, `base`, `type`, and `contents`. Base is just like the output for base_string and the others, type is hard-coded as "group" and contents has a list of fields in it for the elements inside it).
